//=====-- PIC18F4455Subtarget.h - Define Subtarget for the PIC18F4455 ---*- C++ -*--====//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source 
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the PIC18F4455 specific subclass of TargetSubtarget.
//
//===----------------------------------------------------------------------===//

#ifndef PIC18F4455SUBTARGET_H
#define PIC18F4455SUBTARGET_H

#include "llvm/Target/TargetSubtarget.h"

#include <string>

namespace llvm {

class PIC18F4455Subtarget : public TargetSubtarget {

  // IsCooper - Target ISA is Cooper.
  bool IsCooper;

public:
  /// ParseSubtargetFeatures - Parses features string setting specified 
  /// subtarget options.  Definition of function is auto generated by tblgen.
  std::string ParseSubtargetFeatures(const std::string &FS,
                                     const std::string &CPU);
};
} // End llvm namespace

#endif  // PIC18F4455SUBTARGET_H
