##===- lib/Target/PIC18F4455/PIC18F4455Passes/Makefile -----------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source 
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../../..
TARGET = PIC18F4455
LIBRARYNAME = LLVMpic18f4455passes
BUILD_ARCHIVE = 1

include $(LEVEL)/Makefile.common

